buildPack:
  name: gradle
environment:
  RELEASE_NUMBER: BRANCH_NAME
  BKDK_INSTANCE: "bkdk13"
  EMAIL_NOTIFICATION: "emailID@gmail.com"
  RTF_INSTANCE: "enterprise"
  RTF_RELEASE_REPO: "maven-ccap-local"
  RTF_SNAPSHOT_REPO: "maven-ccap-local"
  RTF_VIRTUAL_REPO:
    - "maven-ccap-virtual"
    - "maven-wf-legacy-virtual"
    - "maven-wf-virtual"
    - "maven-external-virtual"
  JDK: "javalljdk-current"
  SNAPSHOT_BUILD: "false"
  CX_PRESET: ALL-EASP-HRA
  LOCAL_WORKSPACE: true
  LOG_LEVEL: DEBUG
  CK_ASYNCHRONOUS: true

applistProperties:
  enablePCCA: false
  codeReviewSubAppID: cardeligibility
  pitest:
    incrementanl: false #Runs PIT in full or incremental mode; default is true
    IsAsyncBuild: true #Runs PIT in parallel of build
    PRBuild:
      params: "pitest"
      enable: false #Disabled by default; must enable if required
    SnapshotBuild:
      params: "pitest"
      enable: false #Disabled by default; must enable if required
    ReleaseBuild:
      parans: "pitest"
      enable: false #Enabled by default
  sonar:
    params: " -Osonar.coverage.exclusions=:bdd/**"
    SONAR_ENV: sonar_prod_poda_dc
    nonDefaultQualityGateID: "903" # Quality gate id to be selected as per application type, see details below
    breakOnFailure: false

  checkmarx:
    enableScan: false
    threadfixllpload: false
    exclude PatternList:
      add: .gradle, moduleInfo\.json, build\/.*\.json, *\/sonar.*\.xml, .*\/build\/.*\.xml, *\build\/\.Json, sonar Timp, sonar Tap
  blackduck:
    artifacts:
      - name: "ccap-cardeligibility.jar"
        groupId: "com.artifactory.ccap-cardeligibility"
        artifactid: ccap-cardeligibility
    isAsyncBuild: true
    disableSWCAUploadAfterScan: true
    threadfixUpload: false

  trufflehog:
    enableScan: true

  components:
    - name: CA03792-cardeligibility
      includePatterns:
        - "ccap-cardeligibility.jar"
        - "manifest.yml"
        - "services.yml"
      groupId: "com.artifactory.ccap-cardeligibility"
      artifactId: ccap-cardeligibility
      
  # TODO: Please update before usage: Modify the below properties as per the deployment requirement
  deploy:
    gateApprovalTimeout: "1h"
    deployViaharness: true
    harness:
      payload:
        serviceID: tascardeligibility    #harness serviceID
        githubBranch: develop    #application config repository githubBranch
        stageIDs: dev, test    # comme seperated list of harness stageIDs
        InputsetIDs: cicdbasicTrigger    #harness inputsetIDs cicbasicTrigger
        environmentID: devtemrclfnn07
        InfrastructureID: tasdevtemrclfnn07
      trigger:
        url: https://app3.harness.io/gateway/pipeline/api/webhook/custom/1110016NRsGq
    dev:
      autoEntryApproval: true
      autoExitApproval: true
      environments:
        - name: dev-temr-clfn-n-07
    qa:
      autoEntryApproval: true
      autoExitApproval: true
      environments:
        - name: sit-sls-clfn-n-07

pipelines:
  release:
    stages:
      - name: Gradle Build
        disable: false
      - name: Inspect
        disable: false
      - name: Publish
        disable: false
      - name: Validate CD Configuration
        disable: true
      - name: Scan
        parallel:
          - name: Blackduck Scan
            disable: false
          - name: Checkmarx Scan
            disable: false
      - name: DEVDeploy
        disable: true
      - name: QADeploy
        disable: true
      - name: PERFDeploy
        disable: true
      - name: PRODDeploy
        disable: true
