buildPack:
  name: gradle
environment:
  RELEASE_NUMBER: BRANCH_NAME
  BKDK_INSTANCE: bkdk13
  EMAIL_NOTIFICATION: emailID@gmail.com
  RTF_INSTANCE: enterprise
  RTF_RELEASE_REPO: maven-ccap-local
  RTF_SNAPSHOT_REPO: maven-ccap-local
  RTF_VIRTUAL_REPO:
  - maven-ccap-virtual
  - maven-wf-legacy-virtual
  - maven-wf-virtual
  - maven-external-virtual
  JDK: javalljdk-current
  SNAPSHOT_BUILD: 'false'
  CX_PRESET: ALL-EASP-HRA
  LOCAL_WORKSPACE: true
  LOG_LEVEL: DEBUG
  CK_ASYNCHRONOUS: true
applistProperties:
  enablePCCA: false
  codeReviewSubAppID: cardeligibility
  pitest:
    incrementanl: false
    IsAsyncBuild: true
    PRBuild:
      params: pitest
      enable: false
    SnapshotBuild:
      params: pitest
      enable: false
    ReleaseBuild:
      parans: pitest
      enable: false
  sonar:
    params: ' -Osonar.coverage.exclusions=:bdd/**'
    SONAR_ENV: sonar_prod_poda_dc
    nonDefaultQualityGateID: '903'
    breakOnFailure: true
  checkmarx:
    enableScan: true
    threadfixllpload: false
    exclude PatternList:
      add: .gradle, moduleInfo\.json, build\/.*\.json, *\/sonar.*\.xml, .*\/build\/.*\.xml,
        *\build\/\.Json, sonar Timp, sonar Tap
  blackduck:
    artifacts:
    - name: ccap-cardeligibility.jar
      groupId: com.artifactory.ccap-cardeligibility
      artifactid: ccap-cardeligibility
    isAsyncBuild: true
    disableSWCAUploadAfterScan: true
    threadfixUpload: false
  trufflehog:
    enableScan: true
  components:
  - name: CA03792-cardeligibility
    includePatterns:
    - ccap-cardeligibility.jar
    - manifest.yml
    - services.yml
    groupId: com.artifactory.ccap-cardeligibility
    artifactId: ccap-cardeligibility
  deploy:
    gateApprovalTimeout: 1h
    deployViaharness: true
    harness:
      payload:
        serviceID: tascardeligibility
        githubBranch: develop
        stageIDs: dev, test
        InputsetIDs: cicdbasicTrigger
        environmentID: devtemrclfnn07
        InfrastructureID: tasdevtemrclfnn07
      trigger:
        url: https://app3.harness.io/gateway/pipeline/api/webhook/custom/1110016NRsGq
    dev:
      autoEntryApproval: true
      autoExitApproval: true
      environments:
      - name: dev-temr-clfn-n-07
    qa:
      autoEntryApproval: true
      autoExitApproval: true
      environments:
      - name: sit-sls-clfn-n-07
pipelines:
  release:
    stages:
    - name: Gradle Build
      disable: false
    - name: Inspect
      disable: false
    - name: Publish
      disable: false
    - name: Validate CD Configuration
      disable: true
    - name: Scan
      parallel:
      - name: Blackduck Scan
        disable: false
      - name: Checkmarx Scan
        disable: false
    - name: DEVDeploy
      disable: false
    - name: QADeploy
      disable: true
    - name: PERFDeploy
      disable: true
    - name: PRODDeploy
      disable: true
RELEASE_NUMBER: 2025.06.27-D
enablepcca: true
